config/routes.rb
Rails.application.routes.draw do
  get '/my_page', to: 'pages#my_page'
  
  resources :categories
  
  devise_for :users

  resources :posts

  # resources :posts do
  #   resources :comments
  # end

  # resources :comments do
  #   resources :comments
  # end

  get '/not_found', to: 'pages#not_found'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'

  get '*path' => redirect('/not_found')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
    has_many :comments, as: :commentable

    validates :body, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category

    # Action Text - available from Rails 6
    has_rich_text :description

    validates :title, length: { minimum: 2, maximum: 40 }
    validates :description, length: { minimum: 10 }

    paginates_per 50
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  validates :nickname, length: { minimum: 2, maximum: 10 }, presence: true, uniqueness: true
  validate :reserved_words

  def reserved_words
      if (/admin/i.match(self.nickname) || /manager/i.match(self.nickname) || /주인/.match(self.nickname) || /운영자/.match(self.nickname) || /관리자/.match(self.nickname) || /매니저/.match(self.nickname) || /오너/.match(self.nickname) || /administrator/i.match(self.nickname) || /exec/i.match(self.nickname) || /ceo/i.match(self.nickname) || /operator/i.match(self.nickname))
        errors.add(:nickname, "사용이 금지된 닉네임입니다.")
      end
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  validates_confirmation_of :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:nickname, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:nickname, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_commentable
before_action :authenticate_user!, except: [:index, :show]

def new
    @comment = Comment.new
end

def create
    @comment = @commentable.comments.new comment_params
    @comment.user = current_user

    if @comment.save
        UserMailer.with(user: @user, comment: @comment).comment_email.deliver_now
        redirect_back(fallback_location: root_path)
     else
    redirect_back(fallback_location: root_path)
    end
end

private

def comment_params
    params.require(:comment).permit(:body)
end

def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def my_page
    if !current_user.nil?
      @user = current_user
    else
      redirect_to root_path, notice: "로그인 해주세요."
    end
  end

  def not_found
    redirect_to root_path, notice: "해당 페이지는 존재하지 않거나 찾을 수 없습니다."
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @categories = Category.all
    
    if(params.has_key?(:category_name) && params[:category_name] != "모든 글")
      puts params[:category_name]
      category_id = Category.where(name: params[:category_name])
      @posts = Post.where(category_id: category_id).order(created_at: :desc).page(params[:page])
    else
      @posts = Post.order(created_at: :desc).page(params[:page])
    end
  end

  def show
    @cagetories = Category.all
  end

  def new
    @post = Post.new
  end

  def edit
    if current_user != @post.user
      redirect_to root_path, notice: "권한이 없습니다."
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '새 글이 작성 되었습니다.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '글이 수정되었습니다.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '글이 삭제 되었습니다.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, notice: "해당 글이 존재하지 않습니다."

    end

    def post_params
      params.require(:post).permit(
        :title,
        :description, 
        :category_id, 
        :telegram, 
        :whatsapp, 
        :discord, 
        :slack, 
        :others,
        :location_id => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
  <%= comment.user.nickname %> -  <small> <%= time_ago_in_words(comment.created_at) %> ago</small>

  <p>
    <%= comment.body %>
  </p>

  <%= form_for [comment, Comment.new] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, placeholder: "Enter here", class: 'form-control' %>
    <%= f.submit "REPLY", class: 'btn btn-info btn-md' %>
  </div>
  <% end %>

  <ul>
      <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

app/views/layouts/_categories.html.erb
<ul class="nav nav-tabs">
  <li class="dropdown">
    <a class="dropdown-toggle"
       data-toggle="dropdown"
       href="#">
        <h5>CATEGORIES</h5>
        <b class="caret"></b>
      </a>
    <ul class="dropdown-menu">
        <li><a href="#">Eat & Drink</a></li>
        <li><a href="#">Coffee & Tea</a></li>
        <li><a href="#">Activities</a></li>
        <li><a href="#">Sports</a></li>
        <li><a href="#">Teach & Learn</a></li>
        <li><a href="#">Online Games</a></li>
        <li><a href="#">Gigs & Events</a></li>
    </ul>
  </li>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'HANVANDO', posts_path, class: 'navbar-brand' %>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to '모든 글', posts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to '새 글 작성', new_post_path, class: 'nav-link' %>
      </li>

      <% if current_user %>
        <li class="nav-item">
          <%= link_to '로그아웃', destroy_user_session_path, class: 'nav-link', method: :delete %>
        </li>
        <li class="nav-item">
          <%= link_to '내 정보', my_page_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to '가입', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to '로그인', user_session_path, class: 'nav-link' %>
        </li>
      <% end %>

      <li class="nav-item">
      <span class="nav-link float-right" style="color: black"><%= Time.now.strftime("%m. %d. %Y") %></span>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hanvando</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
  <%= render 'layouts/navbar' %>

  <div class="container" style="margin-bottom: 50px">
  
  <% unless notice.nil? %>
    <p class="notice" style="color: blue; margin-top: 10px"><%= notice %></p>
  <% end %>

  <% unless alert.nil? %>
    <p class="alert" style="color: red; margin-top: 10px"><%= alert %></p>
  <% end %>
  
  <div style="margin-top: 50px">
    <%= yield %>
  </div>

  </div>
  </body>
</html>

app/views/pages/my_page.html.erb
<h1>내 정보</h1>
<hr>

  <div class="card-body">
    <h5 class="card-title"><%= @user.nickname %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @user.email %></h6>
    <hr>
    <p class="card-text">가입 날짜: <%= @user.created_at.getlocal.strftime("%m. %d. %Y.") %></p>
    <p class="card-text">정보 수정한 날짜: <%= @user.updated_at.getlocal.strftime("%m. %d. %Y.") %></p>
    <%= link_to '내 정보 수정', edit_user_registration_path, class: 'btn btn-warning btn-md' %>
  </div>
<hr>

<% if @user.posts.length > 1 %>
  <h4>내가 작성한 글 들</h4>
<% else %>
  <h4>내가 작성한 글</h4>
<% end %>

<ul class="list-group list-group-flush">
  <% @user.posts.each do |post| %>
    <li class="list-group-item">
      <div class="btn-group" role="group">
          <%= link_to '수정', edit_post_path(post), class: 'btn btn-info btn-sm' %>
          <%= link_to '삭제', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
      </div>
      <div>
      <%= post.created_at.getlocal.strftime("%m. %d. %Y. %l:%M %p") %>
      <%= link_to post.title, post %>
      </div>
    </li>
  <% end %>
</ul>

app/views/pages/not_found.html.erb
<h4>해당 페이지를 찾을 수 없습니다.</h4>

<h4>
<%= link_to '첫 화면으로 돌아가기', posts_path %>
</h4>

app/views/posts/_form.html.erb
<small>*: 필수</small>

<p class="errors">
  <%= @post.errors.full_messages.first if @post.errors.any? %>
</p>

<%= form_with(model: post, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :category, "카테고리*" %>
    <%= f.collection_select(:category_id, Category.where.not(name: "모든 글").all.order("name ASC"), :id, :name, {:prompt => '-'}, {:class => "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.label :title, "제목*" %>
    <%= f.text_field :title, class: "form-control", autofocus: true, placeholder: '...' %>
  </div>

<%# Enter Group Chat Links %>
  <div class="form-group">
    <%= f.label :others, "카카오톡 링크" %>
    <%= f.text_field :others, class: "form-control", placeholder: 'http:// 혹은 https:// 를 포함시켜 주세요' %>
  </div>
  <div class="form-group">
    <%= f.label :telegram, "텔레그램 링크" %>
    <%= f.text_field :telegram, class: "form-control", placeholder: 'http:// 혹은 https:// 를 포함시켜 주세요' %>
  </div>
  <div class="form-group">
    <%= f.label :whatsapp, "왓츠앱 링크" %>
    <%= f.text_field :whatsapp, class: "form-control", placeholder: 'http:// 혹은 https:// 를 포함시켜 주세요' %>
  </div>
  <div class="form-group">
    <%= f.label :discord, "디스코드 링크" %>
    <%= f.text_field :discord, class: "form-control", placeholder: 'http:// 혹은 https:// 를 포함시켜 주세요' %>
  </div>
  <div class="form-group">
    <%= f.label :Slack, "슬랙 링크" %>
    <%= f.text_field :slack, class: "form-control", placeholder: 'http:// 혹은 https:// 를 포함시켜 주세요' %>
  </div>

  <div class="form-group">
    <%= f.label :description, "내용" %>
    <%= f.rich_text_area :description, placeholder: '...'  %>
  </div>

  <%= f.submit "작성", class: "btn btn-primary btn-md" %>
<% end %>

app/views/posts/edit.html.erb
<%= link_to '수정 취소', posts_path, class: 'btn btn-danger btn-md' %>
<%= link_to '원본 보기', @post, class: 'btn btn-warning btn-md' %>
<hr>
<h1>글 수정</h1>
<hr>
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div style="display: flex; justify-content: center">
  <%= paginate @posts %>
</div>

<%# Filter By a Category %>
 <div class="form-group">
    <%= form_tag(posts_path, method: :get) do %> 
      <%= select_tag "category_name", options_from_collection_for_select(@categories.order("created_at ASC"), "name", "name", params[:category_name]), class: 'form-control' %>
      <button class="btn btn-outline-info btn-md btn-block" type="submit">필터</button>
    <% end %>
  </div>

<%# List of Posts %>
<ul class="list-group list-group">
  <% @posts.each do |post| %>
  <li class="list-group-item">
    <%= link_to post.title, post %>

    <p style="margin-top: 5px"><%= post.created_at.getlocal.strftime("%m. %d. %Y. %l:%M %p") %></p>
    

    <%# Edit & Delete Buttons %>
    <% if current_user === post.user %>
      <div class="btn-group" role="group">
          <%= link_to '수정', edit_post_path(post), class: 'btn btn-info btn-sm' %>
          <%= link_to '삭제', post, method: :delete, data: { confirm: '삭제된 글은 복구가 되지 않습니다. 계속 하시겠습니까?' }, class: 'btn btn-danger btn-sm' %>
      </div>
    <% end %>

    <%# Avilable Group Link Icons %>
    <div class="float-right">
    <% if !post.telegram.blank? %>
      <%= link_to "#{post.telegram}" do %>
        <i class="fab fa-telegram fa-lg" style="margin: 0 6px"></i>
      <% end %>
    <% end %>

    <% if !post.whatsapp.blank? %>    
      <%= link_to "#{post.whatsapp}" do %>
        <i class="fab fa-whatsapp fa-lg" style="margin: 0 6px"></i>
      <% end %>
    <% end %>

    <% if !post.discord.blank? %>
      <%= link_to "#{post.discord}" do %>
        <i class="fab fa-discord fa-lg" style="margin: 0 6px"></i>
      <% end %>
    <% end %>

    <% if !post.slack.blank? %>
      <%= link_to "#{post.slack}" do %>
        <i class="fab fa-slack fa-lg" style="margin: 0 6px"></i>
      <% end %>
    <% end %>

    <% if !post.others.blank? %>
      <%= link_to "#{post.others}" do %>
        <i class="fas fa-comments fa-lg" style="margin: 0 6px"></i>
      <% end %>
    <% end %>
    </div>
  </li>
  <% end %>
</ul>

<div style="display: flex; justify-content: center">
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<%= link_to '새 글 작성 취소하고 뒤로가기', posts_path, class: 'btn btn-danger btn-md' %>
<hr>
<h1>새 글</h1>
<hr>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="btn-group" role="group">
  <%= link_to '모든 글 보기', posts_path, class: 'btn btn-primary btn-md' %>
  <% if current_user === @post.user %>
    <%= link_to '수정', edit_post_path(@post), class: "btn btn-info btn-md" %>
    <%= link_to '삭제', @post, method: :delete, data: { confirm: '삭제된 글은 복구가 되지 않습니다. 계속 하시겠습니까?' }, class: 'btn btn-danger btn-md' %>
  <% end %>
</div>
<%# <button class="btn btn-info btn-md float-right">내 페이지에 저장</button> %>

<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @post.title %></h5>
    <p class="card-subtitle mb-2 text-muted">
      작성자: <%= @post.user.nickname %>
    </p>
    <p class="card-subtitle mb-2 text-muted">
      <%= @post.created_at.getlocal.strftime("%m. %d. %Y. %l:%M %p") %>
    </p>

<div style="margin-bottom: 80px">
    <p class="card-text">
      <%= @post.description %>
    </p>
</div>

      <hr>

      <%# Group Chat Links %>
      <h6>그룹 챗 링크</h6>      
      <div style="margin-bottom: 3px;">
      <% if !@post.others.blank? %>
        <%= link_to "#{@post.others}", class: 'btn btn-primary btn-md' do %> 
          <i class="fas fa-comments fa-lg" aria-hidden="true"></i> (카카오톡)
        <% end %>
      <% end %>
      </div>      

      <div style="margin-bottom: 3px;">
        <% if !@post.telegram.blank? %>
          <%= link_to "#{@post.telegram}", class: 'btn btn-primary btn-md' do %>
            <i class="fab fa-telegram fa-lg" aria-hidden="true"></i> (텔레그램)
          <% end %>
        <% end %>
      </div>

      <div style="margin-bottom: 3px;">
      <% if !@post.whatsapp.blank? %>
        <%= link_to "#{@post.whatsapp}", class: 'btn btn-primary btn-md' do %>
          <i class="fab fa-whatsapp fa-lg" aria-hidden="true"></i> (왓츠앱)
        <% end %>
      <% end %>
      </div>

      <div style="margin-bottom: 3px;">
      <% if !@post.discord.blank? %>
        <%= link_to "#{@post.discord}", class: 'btn btn-primary btn-md' do %>
          <i class="fab fa-discord fa-lg" aria-hidden="true"></i> (디스코드)
        <% end %>
      <% end %>
      </div>

      <div style="margin-bottom: 3px;">
      <% if !@post.slack.blank? %>
        <%= link_to "#{@post.slack}", class: 'btn btn-primary btn-md' do %> 
          <i class="fab fa-slack fa-lg" aria-hidden="true"></i> (슬랙)
        <% end %>
      <% end %>
      </div>

  </div>
</div>